name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test list
        id: list
        uses: ./
        with:
          token: ${{ secrets.GH_PAT }}
      - name: echo results
        run: |
          echo ${{ steps.list.outputs.titles }}
          echo ${{ steps.list.outputs.dbg_pullRequests }}
